site_name: ALogin
site_description: Lightweight Python Authentication Library
site_author: Adeep A G
site_url: https://adeep13.github.io/alogin/

theme:
  name: mkdocs
  highlightjs: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Features: features.md
  - Examples: examples.md
  - About: about.md
